name: Independent Jobs

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "Job 1 executed - branch1"

  job2:
    runs-on: ubuntu-latest
    needs: job1 #for dependent jobs
    steps:
      - name: Job 2
        run: echo "Job 2 executed successfully"
